### ISSUE TITLE
ssl cert for www.openbeans.org expired

### ISSUE THREAD

**Issue by reddyshyam** [OpenBeans/OpenBeans#20]
Not sure if this is the place but mentioning hoping it will catch your attention. :)

**Comment by emilianbold** [comment]
Thanks! Renewed!

--emi

**Comment by reddyshyam** [comment]
Thanks @emilianbold. That was quick. 👍

**Comment by emilianbold** [comment]
I had a reminder about it but since you opened the issue... :D Thanks!

--emi
