### ISSUE TITLE
error locating driver for mysql

### ISSUE THREAD

**Issue by KQ-phinks** [OpenBeans/OpenBeans#24]
i already downloaded the mysql driver but anytime i open the filedialog to add the driver it  shows me only the folder but not the jar file (netbeans 12.2) and when i try to open the folder the application hangs
![Screenshot (98)](https://user-images.githubusercontent.com/79951868/109908079-ea754700-7ca3-11eb-94a5-ec8591cfef48.png)

**Comment by emilianbold** [comment]
You are not really using OpenBeans but NetBeans. You can ask more questions about NetBeans 12.2 at https://github.com/apache/netbeans/

That being said, selecting the MySQL connector JAR does work in OpenBeans:

<img width="684" alt="Screenshot 2021-03-04 at 07 23 39" src="https://user-images.githubusercontent.com/991554/109915588-bfe2b880-7cba-11eb-9e21-5c21e1e95953.png">

**Comment by ESCANES** [comment]
opps, sorry my bad
