### ISSUE TITLE
isAbandoned == true?

### ISSUE THREAD

**Issue by goyalyashpal** [OpenBeans/OpenBeans#28]

**Comment by emilianbold** [comment]
Yes.

--emi

vin., 10 nov. 2023, 04:55 goyalyashpal ***@***.***> a scris:

**Comment by goyalyashpal** [comment]
hey! 

a bit offtopic, but what would be your thoughts on using eclipse rather than netbeans?

i tried [searching for it] on ur blog, but found no such results

as for context:
* i am a cs student
* i have used vscodium & intellij idea for standalone java files
* but vscodium aint very good for projects i heard, and intellij seems to be very opaque in its co ant figure out how to us


[searching for it]: http://blog.emilianbold.ro/search?q=eclipse "Emilian Bold's blog: Search results for eclipse"

**Comment by emilianbold** [comment]
Try a few options and see which one fits you best.

--emi

vin., 10 nov. 2023, 13:15 goyalyashpal ***@***.***> a scris:
