### ISSUE TITLE
lite & unbundled package?

### ISSUE THREAD

**Issue by goyalyashpal** [OpenBeans/OpenBeans#29]
the [comparison] page says these things are bundled:

but i don't want any bundled things - it's okay if available as an add-on or separate package.

* Bundled JDK. The macOS/Windows installers include a JDK so you don't need anything else to start coding.
* Java: Bundled nb-javac. For the best Java support.
* JS: Bundled JS libraries.
* JavaFX: Bundled JavaFX libraries.
* Native notifications. All the IDE notification will be shown using the macOS/Windows notification system.

[comparison]: http://www.openbeans.org/comparison.html

**Comment by emilianbold** [comment]
It sounds like you just want plain NetBeans.

--emi

vin., 10 nov. 2023, 04:59 goyalyashpal ***@***.***> a scris:

**Comment by goyalyashpal** [comment]
> It sounds like you just want plain NetBeans.

yes, except for this:

* **Java: Online Maven support.** 
Maven queries will be sent to Maven Central instead of downloading the Maven Central cache which takes GBs of your disk.

**Comment by emilianbold** [comment]
I think... I actually had a separate plugin in the Plugin Portal doing
this. Not sure what happened to it.

I also tried to include this in NetBeans proper. Maybe you can join the
NetBeans mailing list and remind them users want this feature.

--emi

vin., 10 nov. 2023, 08:30 goyalyashpal ***@***.***> a scris:

**Comment by goyalyashpal** [comment]
> Maybe you can join the NetBeans mailing list and remind them users want this feature.

i was thinking of opening an issue upstream directly - i have never joined any mailing list, and i admitting reluctantly, i have fear of joining new things.

**Comment by goyalyashpal** [comment]
here is it 
* https://github.com/apache/netbeans/discussions/6683

**Comment by emilianbold** [comment]
I think you want this plugin
https://github.com/emilianbold/maven.search.remote

--emi
